# Generated by Django 5.0.4 on 2024-04-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sdai", "0002_sdxlimageartifact_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sdxlimageartifact",
            name="payload",
            field=models.TextField(blank=True),
        ),
    ]
